spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: todotrackercapstone@gmail.com
    password: yxerxizoomioyslr
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER



  data:
    mongodb:
      uri: mongodb://localhost:27017/ToDoService

  application:
    name: User-To-Do-Service


eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true

server:
  error:
    include-message: always;
  port: 8003

