server:
  port: 8001
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: todotrackercapstone@gmail.com
    password: yxerxizoomioyslr
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: t
  datasource:
    url: jdbc:mysql://localhost:3306/ToDoTrackerAuthentication
    username: root
    password: ihsak&7991
    driver: com.mysql.cj.jdbc,Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: To-Do-Auth-Service
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true
